import "./styles/variables.css";
import "./styles/reset.css";
import globalStyles from "./styles/global.module.css";

import Header from "../components/Header";
import Navigation from "../components/Navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={globalStyles.bodyWrapper}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
